name: Build and Deploy Nginx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build new Nginx image
      run: |
        ./Dockerfile
        docker build -t my-nginx

    - name: Stop and remove old Nginx container
      run: |
        if [ "$(docker ps -q -f name=my-nginx)" ]; then
          docker stop my-nginx
          docker rm my-nginx
        fi

    - name: Run new Nginx container
      run: |
        docker run -d -p 8080:80 --name my-nginx my-nginx:latest
        docker ps -a

    - name: Test Nginx server
      run: curl -I http://localhost:8080
